[package]
name = "Screener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "1.0.8"

[[bin]]
name = "screener"
path = "src/main.rs"